export const CREATE_ITEM = 'CREATE_ITEM'
export const EDIT_CANVAS = 'EDIT_CANVAS'
export const SET_ACTIVE_ITEM = 'SET_ACTIVE_ITEM'
export const SET_STAGE_REF = 'SET_STAGE_REF'
export const EDIT_WHOLE_CANVAS = 'EDIT_WHOLE_CANVAS'

export const SET_CURRENT_TEMPLATE = 'SET_CURRENT_TEMPLATE'
export const SET_USER_TEMPLATES = 'SET_USER_TEMPLATES'
export const SET_USER_TEMPLATES_LOADING = 'SET_USER_TEMPLATES_LOADING'

export const SET_FONTS = 'SET_FONTS'
export const SET_FONTS_LOADING = 'SET_FONTS_LOADING'
export const ADD_FONT = 'ADD_FONT'