export const CREATE_CERTIFICATE = 'CREATE_CERTIFICATE'
export const SET_CERTIFICATES = 'SET_CERTIFICATES'
export const SET_CURRENT_CERTIFICATE = 'SET_CURRENT_CERTIFICATE'
export const UPDATE_CERTIFICATE = 'UPDATE_CERTIFICATE'
export const DELETE_CERTIFICATE = 'DELETE_CERTIFICATE'

